name: "\U0001F41B Bug Report"
description: Submit a bug report to help us improve infinity
body:
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: | 
        Please share your system info with us (`infinity_emb v2 --help` if installed locally).
        The full command line used that causes issues: 
        OS version: (linux/win/macos)
        Model being used (BAAI/..)
        Hardware used (GPUs/CPU/Accelerator) (`nvidia-smi`): 
        The current version being used:

      placeholder: infinity version, platform, python version, ...
    validations:
      required: true

  - type: checkboxes
    id: information-scripts-examples
    attributes:
      label: Information
      description: 'The problem arises when using:'
      options:
        - label: "Docker + cli"
        - label: "pip + cli"
        - label: "pip + usage of Python interface"

  - type: checkboxes
    id: information-tasks
    attributes:
      label: Tasks
      description: "The thing I am working on is:"
      options:
        - label: "An officially supported CLI command"
        - label: "My own modifications"

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a code sample that reproduces the problem you ran into. It can be a Colab link or just a code snippet.
        If you have code snippets, error messages, stack traces please provide them here as well.
        Important! Use code tags to correctly format your code. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting
        Do not use screenshots, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        Steps to reproduce the behavior:
          
          1.
          2.
          3.

        Expected behavior:
          ..
        
          

