name: "\U0001F31F Model support"
description: Submit a proposal/request to implement a new model
labels: [ "New model" ]

body:
  - type: textarea
    id: description-request
    validations:
      required: true
    attributes:
      label: Model description
      description: |
        Put any and all important information relative to the model

  - type: checkboxes
    id: information-tasks
    attributes:
      label: Open source status
      description: |
          Please note that if the model implementation isn't available in `transformers`, the model can't be loaded.
      options:
        - label: "The model implementation is available on transformers"
        - label: "The model weights are available on huggingface-hub"
        - label: "I verified that the model is currently not running in the lastest version `pip install infinity_emb[all] --upgrade`"

  - type: textarea
    id: additional-info
    attributes:
      label: Provide useful links for the implementation
      description: |
        Please provide information regarding the implementation, the weights, and the authors.
        Please mention the authors by @gh-username if you're aware of their usernames.
